version: '3'
services:
  nginx:
    image: 'nginx:stable-alpine'
    container_name: nginx
    env_file: .env
    networks:
      - dmz
      - internal
    ports:
      - '${HTTP_PORT}:80'
    volumes:
      - './config/nginx/nginx.conf:/etc/nginx/nginx.conf'
      - './config/nginx/iot-edge.conf:/etc/nginx/iot-edge.conf'
      - './config/nginx/iot-edge.conf.template:/etc/nginx/iot-edge.conf.template'
      - './config/nginx/startup.sh:/startup.sh'
      - './log/nginx:/tmp/logs'
    restart: always
    depends_on:
      - nodered
      - graphite
      - grafana
      - edge
    command: ['sh', '-c', '/startup.sh']
  graphite:
    image: 'graphiteapp/graphite-statsd:1.1.4'
    container_name: graphite
    env_file: .env
    networks:
      - internal
    # ports:
    #   - '8080:80'
    #   - '2003-2004:2003-2004'
    #   - '2023-2024:2023-2024'
    #   - '8125:8125/udp'
    #   - '8126:8126'
    volumes:
      - './config/graphite/local_settings.py:/opt/graphite/webapp/graphite/local_settings.py'
      - './config/graphite/carbon.conf:/opt/graphite/conf/carbon.conf'
      - './config/graphite/storage-aggregation.conf:/opt/graphite/conf/storage-aggregation.conf'
      - './config/graphite/storage-schemas.conf:/opt/graphite/conf/storage-schemas.conf'
      - './config/graphite/statsd-config.js:/opt/statsd/config_udp.js'
      - './config/graphite/startup.sh:/startup.sh'
      - './data/graphite/storage:/opt/graphite/storage'
      - './log/graphite:/var/log'
      - './log/graphite:/tmp/logs'
    restart: always
    command: ['sh', '-c', '/startup.sh']
  mqtt:
    image: 'eclipse-mosquitto:1.5'
    container_name: mqtt
    env_file: .env
    networks:
      - dmz
      - internal
    ports:
      - '${MQTT_PORT}:1883'
      - '${MQTT_WS_PORT}:9001'
    volumes:
      - './config/mqtt:/mosquitto/config'
      - './config/mqtt/startup.sh:/startup.sh'
      - './data/mqtt:/mosquitto/data'
      - './log/mqtt:/var/log'
      - './log/mqtt:/tmp/logs'
    restart: always
    command: ['sh', '-c', '/startup.sh']
  nodered:
    image: 'iotedge/node-red:1.0.7'
    container_name: nodered
    env_file: .env
    depends_on:
      - mqtt
    networks:
      - internal
    # ports:
    #   - '1880:1880'
    volumes:
      - './config/nodered/settings.js:/data/settings.js'
      - './config/nodered/startup.sh:/startup.sh'
      - './data/nodered:/data'
      - './log/nodered:/var/log'
      - './log/nodered:/tmp/logs'
    depends_on:
      - 'mqtt'
    restart: always
    command: ['sh', '-c', '/startup.sh']
  grafana:
    image: 'grafana/grafana:6.1.6'
    container_name: grafana
    env_file: .env
    networks:
      - internal
    # ports:
    #   - '3000:3000'
    depends_on:
      - 'loki'
    volumes:
      - './config/grafana:/etc/grafana'
      - './config/grafana/startup.sh:/startup.sh'
      - './data/grafana:/var/lib/grafana'
      - './log/grafana:/var/log/grafana'
      - './log/grafana:/tmp/logs'
    restart: always
    entrypoint: ['sh', '-c', '/startup.sh']
  edge:
    image: 'iotedge/server:2.3.3'
    container_name: edge
    env_file: .env
    environment:
      NODE_CONFIG_DIR: /mnt/config/edge
    networks:
      - internal
    depends_on:
      - nodered
      - graphite
      - grafana
    # ports:
    #   - '9002:9002'
    volumes:
      - '.:/mnt'
      - './config/edge/startup.sh:/startup.sh'
      - './log/edge:/tmp/logs'
      # For iot-edge server development:
      #   git clone https://github.com/iot-edge/iot-edge.git
      #   Uncomment the line below and run "npm restart"
      #   Run "docker-compose restart edge" to reload changes
      # - '/path/to/cloned/iot-edge:/usr/local/lib/node_modules/iot-edge'
    restart: always
    command: ['sh', '-c', '/startup.sh']
  loki:
    image: 'grafana/loki:latest'
    container_name: loki
    networks:
      - internal
    # ports:
    #   - '3100:3100'
    volumes:
      - './config/loki:/etc/loki'
      - './config/loki/startup.sh:/startup.sh'
      - './data/loki:/tmp/loki'
      - './log/loki:/tmp/logs'
    restart: always
    entrypoint: ['sh', '-c', '/startup.sh']
  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - './config/promtail:/etc/promtail'
      - './config/promtail/startup.sh:/startup.sh'
      - './data/promtail:/promdata'
      - './log/promtail:/tmp/logs'
      - './log:/log'
    networks:
      - internal
    # ports:
    #   - '9080:9080'
    depends_on:
      - 'loki'
    entrypoint: ['sh', '-c', '/startup.sh']
networks:
  dmz:
    driver: bridge
  internal:
    driver: bridge
