version: '3'
services:
  nginx:
    image: 'nginx:stable-alpine'
    container_name: nginx
    env_file: .env
    networks:
      - dmz
      - internal
    ports:
      - '${HTTP_PORT}:80'
    volumes:
      - './config/nginx/nginx.conf:/etc/nginx/nginx.conf'
      - './config/nginx/iot-edge.conf:/etc/nginx/iot-edge.conf'
      - './config/nginx/iot-edge.conf.template:/etc/nginx/iot-edge.conf.template'
      - './config/nginx/startup.sh:/etc/nginx/startup.sh'
    restart: always
    depends_on:
      - nodered
      - graphite
      - grafana
      - edge
    command: ['sh', '-c', '/etc/nginx/startup.sh']
  graphite:
    image: 'graphiteapp/graphite-statsd:1.1.4'
    container_name: graphite
    env_file: .env
    networks:
      - internal
    # ports:
    #   - '8080:80'
    #   - '2003-2004:2003-2004'
    #   - '2023-2024:2023-2024'
    #   - '8125:8125/udp'
    #   - '8126:8126'
    volumes:
      - './config/graphite/local_settings.py:/opt/graphite/webapp/graphite/local_settings.py'
      - './config/graphite/carbon.conf:/opt/graphite/conf/carbon.conf'
      - './config/graphite/storage-aggregation.conf:/opt/graphite/conf/storage-aggregation.conf'
      - './config/graphite/storage-schemas.conf:/opt/graphite/conf/storage-schemas.conf'
      - './config/graphite/statsd-config.js:/opt/statsd/config_udp.js'
      - "./data/graphite:/opt/graphite/storage"
      - "./data/graphite/log:/var/log"
    restart: always
  mqtt:
    image: 'eclipse-mosquitto:1.5'
    container_name: mqtt
    env_file: .env
    networks:
      - dmz
      - internal
    ports:
      - '${MQTT_PORT}:1883'
      - '${MQTT_WS_PORT}:9001'
    volumes:
      - './config/mqtt:/mosquitto/config'
      - './data/mqtt:/mosquitto/data'
    restart: always
  nodered:
    image: 'microclimates/iot-edge-node-red:1.0.6'
    container_name: nodered
    env_file: .env
    depends_on:
      - mqtt
    networks:
      - internal
    # ports:
    #   - '1880:1880'
    volumes:
      - './config/node-red/settings.js:/data/settings.js'
      - './data/node-red:/data'
    restart: always
    depends_on:
      - "mqtt"
  grafana:
    image: 'grafana/grafana:6.1.6'
    container_name: grafana
    env_file: .env
    networks:
      - internal
    # ports:
    #   - '3000:3000'
    depends_on:
      - "loki"
    volumes:
      - './config/grafana:/etc/grafana'
      - './data/grafana/log:/var/log/grafana'
      - './data/grafana:/var/lib/grafana'
    restart: always
    entrypoint: ['sh', '-c', '/etc/grafana/startup.sh']
  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - './config/promtail:/etc/promtail'
      - './data/promtail:/promdata'
    command: -config.file=/etc/promtail/docker-config.yaml
    networks:
      - internal
    # ports:
    #   - '9080:9080'
    depends_on:
      - "loki"
  loki:
    image: 'grafana/loki:latest'
    container_name: loki
    networks:
      - internal
    # ports:
    #   - '3100:3100'
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - './config/loki:/etc/loki'
      - './data/loki:/tmp/loki'
    restart: always
  edge:
    image: 'microclimates/iot-edge-server:2.3.2'
    container_name: edge
    env_file: .env
    environment:
      NODE_CONFIG_DIR: /mnt/config/edge
    networks:
      - internal
    depends_on:
      - nodered
      - graphite
      - grafana
    # ports:
    #   - '9002:9002'
    volumes:
      - '.:/mnt'
      # For iot-edge server development:
      #   git clone https://github.com/microclimates/iot-edge.git
      #   Uncomment the line below and run "npm restart"
      #   Run "docker-compose restart edge" to reload changes
      # - '/path/to/cloned/iot-edge:/usr/local/lib/node_modules/iot-edge'

    restart: always
networks:
  dmz:
    driver: bridge
  internal:
    driver: bridge